apiVersion: v1
kind: Service
metadata:
  name: namenode
  namespace: hadoop
spec:
  ports:
    - port: 9870
      name: web
    - port: 9000
      name: rpc
  selector:
    app: namenode
---
apiVersion: v1
kind: Service
metadata:
  name: datanode
  namespace: hadoop
spec:
  clusterIP: None # Headless service để phân giải DNS chuẩn
  ports:
    - port: 9864
      name: web
    - port: 9866
      name: data
    - port: 9867
      name: ipc
  selector:
    app: datanode
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namenode
  namespace: hadoop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namenode
  template:
    metadata:
      labels:
        app: namenode
    spec:
      containers:
      - name: namenode
        image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: CLUSTER_NAME
          value: "test"
        - name: CORE_CONF_fs_defaultFS
          value: "hdfs://namenode:9000"
        - name: HDFS_CONF_dfs_replication
          value: "1"
        - name: HDFS_CONF_dfs_permissions_enabled
          value: "false"
        # --- QUAN TRỌNG: Client phải dùng hostname để kết nối ---
        - name: HDFS_CONF_dfs_client_use_datanode_hostname
          value: "true"
        # --------------------------------------------------------
        # Vẫn giữ lệnh tắt kiểm tra DNS
        command: ["/bin/bash", "-c"]
        args:
          - |
            sed -i '/<configuration>/a <property><name>dfs.namenode.datanode.registration.ip-hostname-check</name><value>false</value></property>' /etc/hadoop/hdfs-site.xml &&
            /entrypoint.sh /run.sh
        ports:
        - containerPort: 9870
          name: web
        - containerPort: 9000
          name: rpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datanode
  namespace: hadoop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datanode
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
      - name: datanode
        image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
        resources:
          requests:
            memory: "4Gi"
            cpu: "1000m"
        env:
        - name: SERVICE_PRECONDITION
          value: "namenode:9870"
        - name: CORE_CONF_fs_defaultFS
          value: "hdfs://namenode:9000"
        - name: HDFS_CONF_dfs_replication
          value: "1"
        - name: HDFS_CONF_dfs_permissions_enabled
          value: "false"
        # --- QUAN TRỌNG: DataNode ép buộc dùng tên định danh này ---
        - name: HDFS_CONF_dfs_datanode_hostname
          value: "datanode.hadoop.svc.cluster.local"
        # -----------------------------------------------------------
        command: ["/bin/bash", "-c"]
        args:
          - |
            sed -i '/<configuration>/a <property><name>dfs.namenode.datanode.registration.ip-hostname-check</name><value>false</value></property>' /etc/hadoop/hdfs-site.xml &&
            /entrypoint.sh /run.sh
        volumeMounts:
        - mountPath: /hadoop/dfs/data
          name: datanode-storage
      volumes:
      - name: datanode-storage
        emptyDir: {}